### ISSUE TITLE
268:processed_observation = np.maximum(observation, last_observation)

### ISSUE THREAD

**Issue by shaomai00** [tatsuyaokubo/dqn#3]
what dose this code mean? I'm a little confused 
please help ~

**Comment by TheClassyPenguin** [comment]
I was wondering too. What's the reasoning behind the selection of the previous observation rather than the current one? And how does np.maximum do that?

**Comment by TheClassyPenguin** [comment]
@shaomai00 I think i've found what it's supposed to be doing. Apparently is a vestigial piece of code from the original papel (not using GYM) in which every time an action was made skipped exactly 4 frames. This made it so that sometimes it was difficult or impossible to see some objects that's why the frames could be added up. This is no longer an issue as it uses GYM.

**Comment by shaomai00** [comment]
@TheClassyPenguin thank u very much~
